### ISSUE TITLE
Include all Elm files recursively

### ISSUE THREAD

**Issue by erkal** [gacallea/elm_vite_tailwind_template#6]
I think [this line](https://github.com/gacallea/elm_vite_tailwind_template/blob/bb4ce384f68545dbb9a981fef0f9f6808d6d2478/tailwind.config.js#L6) should be `./src/elm/**/*.elm`. It took me a lot of time to find this out :). I was almost quitting the idea of using this template.
Now it works perfectly. Thank you for doing this! ❤️

**Comment by gacallea** [comment]
Ciao @erkal !

thank you for opening this issue, I appreciate :)

it should be fixed now, let me know :)

**Comment by gacallea** [comment]
ps: looking forward to see what you do with this. please share if possible/you fancy :)
